FROM python:3.12-alpine

ENV POETRY_VIRTUALENVS_CREATE=false

RUN pip install poetry

WORKDIR /app
COPY pyproject.toml poetry.lock ./
RUN poetry install
COPY courses*.json .

WORKDIR /app/flaskr
COPY flaskr .

WORKDIR /app
ENV PORT=8080
CMD ["gunicorn", "-w", "4", "flaskr:create_app()", "-b", "0.0.0.0:5000"]
