FROM python:3.12-alpine

ENV POETRY_VIRTUALENVS_CREATE=false

RUN pip install poetry

WORKDIR /app
COPY pyproject.toml poetry.lock ./
RUN poetry install
COPY courses*.json .

WORKDIR /app/flaskr
COPY flaskr .

WORKDIR /app
COPY run_server.sh .
RUN chmod +x run_server.sh
ENV PORT=5000
CMD ["/bin/sh", "-c", "./run_server.sh"]
