services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tmp
      - MONGO_INITDB_ROOT_PASSWORD=tmp
    ports:
      - "27017:27017"
    volumes:
      - './database/data:/data/db'
    command: --quiet
  cu2m-backend:
    build: .
    ports:
      - 8080:8080

    environment:
      MONGO_DB_USERNAME: tmp
      MONGO_DB_PASSWORD: tmp
      MONGODB_URI: mongodb://tmp:tmp@mongodb:27017/ 
    develop:
      watch:
        - action: sync+restart
          path: ./flaskr
          target: /app/flaskr
          ignore:
            - __pycache__/
        - action: rebuild
          path: requirements.txt
