services:
  mongodb:
    profiles: [debug, prod]
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tmp
      - MONGO_INITDB_ROOT_PASSWORD=tmp
    ports:
      - 27017:27017
    volumes:
      - './database/data:/data/db'
    command: --quiet
  cu2m-backend-debug:
    profiles: [debug]
    build:
      context: .
      dockerfile: Debug.Dockerfile
    environment:
      - COURSE_DATA_FILENAME=courses.json
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_PORT=27017
      - LOGGING_LEVEL=DEBUG
    ports:
      - 8081:8080
    volumes:
      - './flaskr:/app/flaskr'
    develop:
      watch:
        - action: restart
          path: ./flaskr
          ignore:
            - __pycache__/
        - action: rebuild
          path: pyproject.toml
  cu2m-backend:
    profiles: [prod]
    build: .
    environment:
      - COURSE_DATA_FILENAME=courses.json
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_PORT=27017
      - LOGGING_LEVEL=INFO
    ports:
      - 8080:8080

