name: Test with Pytest in Docker Compose

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
      MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
      MONGO_DB_HOST: localhost
      MONGO_DB_PORT: 27017
      COURSE_DATA_FILENAME: ${{ vars.COURSE_DATA_FILENAME }}
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: tmp
          MONGO_INITDB_ROOT_PASSWORD: tmp
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'poetry'
      - name: Create virtual env and run test
        run: |
          pip install poetry
          poetry install
          pytest --log-cli-level=INFO
